apiVersion: v1
kind: Service
metadata:
  name: {{ include "osp.fullname" . }}-fe
  labels:
    {{- include "osp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceFe.type }}
  ports:
    - port: {{ .Values.serviceFe.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ospFe.selectorLabels" . | nindent 4 }}
